[book]
authors = ["noarch"]
language = "zh-Hans"
multilingual = false
src = "src"
title = "privacy.noarch"

[output.html]
# disable automatic dark theme to not break images
preferred-dark-theme = "light"

# add custom TOC, fonts, and unsafe browser detection
additional-css = ["sidebar.css", "fonts.css", "unsafeBrowserBanner.css"]
additional-js = ["sidebar.js", "browserDetection.js", "unsafeBrowserBanner.js"]

# do not use webfonts other than FA, speeds up loading and saves bandwidth
copy-fonts = false

# link to repository
git-repository-url = "https://git.n0ar.ch/privacy"
git-repository-icon = "fa-git"
