name: Deploy to Cloudflare pages

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      - name: Retrieve the latest mdBook release by noarchwastaken
        run: |
          wget https://github.com/noarchwastaken/mdBook/releases/download/v0.4.7-noarchwastaken/mdbook-v0.4.7-noarchwastaken-x86_64-unknown-linux-gnu.tar.gz
          tar -xvf mdbook-v0.4.7-noarchwastaken-x86_64-unknown-linux-gnu.tar.gz

      - name: Install BeautifulSoup for lazyimg.py
        run: sudo apt install python3-bs4 -y

      - name: Build the book
        run: |
          ./mdbook build

      - name: Patch the output for lazy image loading
        run: python3 utils/lazyimg.py book

      - name: Push the book to the CF pages repo
        uses: cpina/github-action-push-to-another-repository@master
        env:
          API_TOKEN_GITHUB: ${{ secrets.API_TOKEN_GITHUB }}
        with:
          source-directory: 'book'
          destination-github-username: 'noarchwastaken'
          destination-repository-name: 'privacy-pages'
          user-email: notareal@email.com
